#include<iostream.h>
#include<conio.h>
void main()
 {clrscr();
 int a;
 cout<<"enter an integer:";
 cin>>a;
 long int b;
 cout<<"enter a long integer:";
 cin>>b;
 float c;
 cout<<"enter a float:";
 cin>>c;
 double d;
 cout<<"enter a double:";
 cin>>d;
 long double e;
 cout<<"enter a long double:";
 cin>>e;
 char ch;
 cout<<"enter a character:";
 cin>>ch;
 cout<<"you entered an integer:"<<a<<endl<<"you entered a long integer:"<<b
 <<endl<<"you entered a float:"<<c<<endl<<"you entered a double:"<<d<<endl<<
 "you entered a long double:"<<e<<endl<<"you entered a character:"<<ch<<endl;
 }