#include<iostream.h>
#include<conio.h>
void main()
{clrscr();
int month;
cout<<"enter a month number to know the no of days in it:";
cin>>month;
 if(month==1)
 cout<<"january has 31 days.";

 else if(month==2)
 cout<<"february has either 28 or 29 days.";

 else if(month==3)
 cout<<"march has 31 days.";

 else if(month==4)
 cout<<"april has 30 days.";

 else if(month==5)
 cout<<"may has 31 days.";

 else if(month==6)
 cout<<"june has 30 days.";

 else if(month==7)
 cout<<"july has 31 days.";

 else if(month==8)
 cout<<"august has 31 days.";

 else if(month==9)
 cout<<"september has 30 days.";

 else if(month==10)
 cout<<"october has 31 days.";

 else if(month==11)
 cout<<"november has 30 days.";

 else if(month==12)
 cout<<"december has 31 days.";

 else
 cout<<"invalid, enter a month number between 1 & 12";

 }